language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  only:
    - master

before_install:
  - set -e
  - python -V

install:
  - pip install pip wheel --upgrade
  - pip install -r requirements.txt
  - pip install flake8
  - python setup.py build && python setup.py install

script:
  - python -m flake8 libgsync --config=.flake8rc
