language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

sudo: false

branches:
    only:
        - master

before_install:
    - set -e

install:
    - pip install -r requirements.txt
    - python setup.py build && python setup.py install

script:
    - echo
